# Generated by Django 2.0.7 on 2018-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField()),
                ('logo', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_Date', models.DateField()),
                ('total_morning_date', models.TimeField()),
                ('total_afternoon_date', models.TimeField()),
                ('total_evening_date', models.TimeField()),
            ],
        ),
    ]
