# Generated by Django 2.0.7 on 2018-07-30 19:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muduryardimci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_check', models.CharField(max_length=255, unique=True)),
                ('check_morning', models.TimeField()),
                ('check_afternoon', models.TimeField()),
                ('check_evening', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to=settings.AUTH_USER_MODEL)),
                ('trainess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainess_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(help_text='E-Mail Adresinizi Girmeniz Gerekmektedir.', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefon numaranız 5340775723 şeklinde girilmelidir. "\n                                         "14 haneye kadar izin verilir. ', regex='^\\+?1?\\d{9,15}$')])),
                ('telegram_username', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='total_afternoon_date',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='total_evening_date',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='total_morning_date',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='notes',
            name='site_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_id', to='muduryardimci.Site'),
        ),
        migrations.AddField(
            model_name='notes',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
