# Generated by Django 2.0.7 on 2018-07-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muduryardimci', '0003_auto_20180730_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='course_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Check_Course_id', to='muduryardimci.Courses'),
        ),
        migrations.AddField(
            model_name='check',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Check_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='authorized_trainer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='authorized_trainer_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='trainer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='trainess',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trainess_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='site_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Note_site_id', to='muduryardimci.Site'),
        ),
        migrations.AlterField(
            model_name='note',
            name='trainer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Note_trainer_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Note_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
