# Generated by Django 2.0.7 on 2018-07-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muduryardimci', '0005_auto_20180730_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='site_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Note_site_id', to='muduryardimci.Site'),
        ),
    ]
