# Generated by Django 2.0.7 on 2018-07-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muduryardimci', '0007_auto_20180731_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_morning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='site_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Note_site_id', to='muduryardimci.Site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
