# Generated by Django 2.0.7 on 2018-07-31 18:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muduryardimci', '0010_auto_20180731_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Telefon numaranız 5340775723 şeklinde girilmelidir."\n                                          14 haneye kadar izin verilir. ', regex='^\\+?1?\\d{9,15}$')])),
                ('telegram_username', models.CharField(max_length=25)),
                ('course_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='muduryardimci.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='site_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Note_site_id', to='muduryardimci.Site'),
        ),
    ]
